spring.datasource.url=jdbc:h2:file:./atg-data;MODE=PostgreSQL;AUTO_SERVER=TRUE;NON_KEYWORDS=VALUE,YEAR,DAY,TYPE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
